INSERT INTO PRODUCT(ID, NAME,DESCRIPTION ) VALUES (1,'Dell Laptop', 'With i3');
INSERT INTO PRODUCT(ID, NAME,DESCRIPTION ) VALUES (2,'HP Laptop', 'With i5');

INSERT INTO CONFIG(ID, NAME, DESCRIPTION) VALUES (1,'x64', '64 bit');
INSERT INTO CONFIG(ID, NAME, DESCRIPTION) VALUES (2,'x32', '32 bit');

INSERT INTO USER(ID, USERNAME, PASSWORD) VALUES(1, 'testuser1', '$2a$10$xLUV9zyknp0oMRrV8HLUyOI3t/0roXX2wGIMPjtr48qc.3a..45kO');
INSERT INTO USER(ID, USERNAME, PASSWORD) VALUES(2, 'testuser2', '$2a$10$.I6JUZn34ZDa9Vg9SeKUHO.AI7jGIMJrMy5HfBFDeDoITCjIcGyUa');
INSERT INTO USER(ID, USERNAME, PASSWORD) VALUES(3, 'testuser3', '$2a$10$9bo.qDzM//2LwwO1q3pV1OpGIt.q.4Ve3R8opYIDLA2Ow82XSbGAi');